<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Московское время (зима)">
<General productName="Vugen" productVer="12" os="" host="KEANU-ПК"><DocLocation><![CDATA[E:\Users\Keanu\work\webtour\scripts\webtour_03_register_new_accounts]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[webtour_03_register_new_accounts]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Service: Reg Save Param RegExp]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>ParamName = <STRONG><FONT COLOR=#00AF00>userSession</FONT></STRONG><BR>RegExp = <STRONG><FONT COLOR=#00AF00>name="userSession"\ value="(.*?)"/>\
<table\ border</FONT></STRONG><BR>Instance = <STRONG><FONT COLOR=#00AF00>[param not passed in call]</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:47]]></Time>
<TimeTick>1504082567</TimeTick>
<NodeArgs eType="General" icon="3" nRep="6" >
<Disp><![CDATA[Service: Reg Save Param RegExp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Url: WebTours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:47]]></Time>
<TimeTick>1504082567</TimeTick>
<NodeArgs eType="General" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Url: WebTours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Url: header.html]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:47]]></Time>
<TimeTick>1504082567</TimeTick>
<NodeArgs eType="General" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[Url: header.html]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t3.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:47" eTime="30.08.2017 - 11:42:47" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" status="Passed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T6" iterID="1" >
<Action rID="T7">
<AName><![CDATA[Action]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="4" nRep="12" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="6" nRep="13" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:47" eTime="30.08.2017 - 11:42:48" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="11" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T10" iterID="2" >
<Action rID="T11">
<AName><![CDATA[Action]]></AName>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="4" nRep="18" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="6" nRep="19" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:48" eTime="30.08.2017 - 11:42:48" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="17" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="16" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T14" iterID="3" >
<Action rID="T15">
<AName><![CDATA[Action]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="4" nRep="24" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="6" nRep="25" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:48" eTime="30.08.2017 - 11:42:48" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="23" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="22" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T18" iterID="4" >
<Action rID="T19">
<AName><![CDATA[Action]]></AName>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="4" nRep="30" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="6" nRep="31" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:48" eTime="30.08.2017 - 11:42:48" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="29" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="28" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T22" iterID="5" >
<Action rID="T23">
<AName><![CDATA[Action]]></AName>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:48]]></Time>
<TimeTick>1504082568</TimeTick>
<NodeArgs eType="General" icon="4" nRep="36" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration5\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="6" nRep="37" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration5\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:48" eTime="30.08.2017 - 11:42:49" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="35" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="34" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T26" iterID="6" >
<Action rID="T27">
<AName><![CDATA[Action]]></AName>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="4" nRep="42" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration6\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="6" nRep="43" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration6\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:49" eTime="30.08.2017 - 11:42:49" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="41" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="40" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 6 (Row 6)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T30" iterID="7" >
<Action rID="T31">
<AName><![CDATA[Action]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="4" nRep="48" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration7\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="6" nRep="49" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration7\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:49" eTime="30.08.2017 - 11:42:49" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="47" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="46" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 7 (Row 7)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T34" iterID="8" >
<Action rID="T35">
<AName><![CDATA[Action]]></AName>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="4" nRep="54" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration8\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="6" nRep="55" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration8\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:49" eTime="30.08.2017 - 11:42:49" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="53" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="52" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 8 (Row 8)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T38" iterID="9" >
<Action rID="T39">
<AName><![CDATA[Action]]></AName>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="4" nRep="60" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration9\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="6" nRep="61" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration9\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:49" eTime="30.08.2017 - 11:42:49" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="59" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="58" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 9 (Row 9)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T42" iterID="10" >
<Action rID="T43">
<AName><![CDATA[Action]]></AName>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:49]]></Time>
<TimeTick>1504082569</TimeTick>
<NodeArgs eType="General" icon="4" nRep="66" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration10\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="6" nRep="67" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration10\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:49" eTime="30.08.2017 - 11:42:50" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="65" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="64" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 10 (Row 10)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T46" iterID="11" >
<Action rID="T47">
<AName><![CDATA[Action]]></AName>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="4" nRep="72" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration11\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="6" nRep="73" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration11\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:50" eTime="30.08.2017 - 11:42:50" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="71" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="70" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 11 (Row 11)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T50" iterID="12" >
<Action rID="T51">
<AName><![CDATA[Action]]></AName>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="4" nRep="78" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration12\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="6" nRep="79" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration12\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:50" eTime="30.08.2017 - 11:42:50" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="77" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="76" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 12 (Row 12)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T54" iterID="13" >
<Action rID="T55">
<AName><![CDATA[Action]]></AName>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="4" nRep="84" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration13\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="6" nRep="85" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration13\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:50" eTime="30.08.2017 - 11:42:50" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="83" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="82" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 13 (Row 13)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T58" iterID="14" >
<Action rID="T59">
<AName><![CDATA[Action]]></AName>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="4" nRep="90" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration14\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:50]]></Time>
<TimeTick>1504082570</TimeTick>
<NodeArgs eType="General" icon="6" nRep="91" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration14\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:50" eTime="30.08.2017 - 11:42:50" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="89" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="88" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 14 (Row 14)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T62" iterID="15" >
<Action rID="T63">
<AName><![CDATA[Action]]></AName>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:51]]></Time>
<TimeTick>1504082571</TimeTick>
<NodeArgs eType="General" icon="4" nRep="96" status="Passed" >
<Disp><![CDATA[Url: login.pl]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration15\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Submit Data: login.pl_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[30.08.2017 - 11:42:51]]></Time>
<TimeTick>1504082571</TimeTick>
<NodeArgs eType="General" icon="6" nRep="97" status="Passed" >
<Disp><![CDATA[Submit Data: login.pl_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration15\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="30.08.2017 - 11:42:50" eTime="30.08.2017 - 11:42:51" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="95" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="94" status="Passed" >
<Disp><![CDATA[webtour_03_register_new_accounts Iteration 15 (Row 15)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T66" iterID="16" >
<Action rID="T67">
<AName><![CDATA[Action]]></AName>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Url: login.pl]]></Obj>